fruits=["apple", "pear","cherry"]
print(fruits)
fruits.append("blueberry")
print(fruits)
fruits.insert(2,"strawberry")
print(fruits)
fruits.remove("pear")
print(fruits)
fruits.reverse()
print(fruits)
fruits.pop(1)
print(fruits)

print(fruits[2])
fruits.append("pinnaeaple")
fruits.append("pear")
fruits.append("watermelon")

fruits.sort()
print(fruits)
